name: orecrushmining
version: '${version}'
main: me.yirf.orecrushmining.Orecrushmining
api-version: '1.20'
depend:
  - packetevents
commands:
  ocm:
    description: OreCrush mining commands.
    aliases:
      - ocmining
      - orecrushmining